### ISSUE TITLE
Brak możliwości zmiany pliku "index.html" w swoim folderze

### ISSUE THREAD

**Issue by ghost** [pict-html-swps/project1#1]
Ogólnie rzecz biorąc, nie śmiga zmiana indexu. Mój kod nie ma w sobie "hi" a jednak cały czas mi się wyświetla.

**Comment by idrach** [comment]
:(

**Comment by Mawrr** [comment]
smutno mi, Boże

**Comment by ghost** [comment]
:-1:

**Comment by mrozbicki** [comment]
Nie marte się. Dzieci z rakiem mają gorzej.

2015-11-06 18:11 GMT+01:00 Adela Sznajder notifications@github.com:

> smutno mi, Boże
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pict-html-swps/project1/issues/1#issuecomment-154475302
> .

## 

Szkoła Wyższa Psychologii Społecznej
http://www.swps.pl

**Comment by ghost** [comment]
A Piotr nie wie jak z tego korzystać :D

**Comment by speplinski** [comment]
done
